### PR TITLE
Allow user to specify max number of pending connections to a server

### LINKED ISSUE #991: Add a new WebSocketServer constructor allowing  to specify the maximum number of pending connections
After running some load tests on our company's app, I found that is not possible to specify the maximum number of pending connections (backlog) for the WebSocketServer. 

I would be very interested in having a new WebSocketServer constructor that receives a new parameter in order to specify the backlog here `socket.bind( address )`.

Thanks

### PR DESCRIPTION
**Pull request by PhilipRoman**
~~Theoretically I should add this to 1.5.0 milestone, but since this is a non-breaking change and we also have a non-breaking #1000, so maybe there should be a small 1.4.2 release so that people can use these improvements without breaking changes of 1.5.0? I will add the appropriate @​since tags to JavaDoc when this is decided.~~

## Description

Adds a field and two new methods to WebSocketServer: `setMaxPendingConnections(int)` and `getMaxPendingConnections()` and uses the value as a parameter when binding the server socket.

## Related Issue

Fixes #991

## Motivation and Context

This change allows users to configure the maximum number of pending connections.

## How Has This Been Tested?

Existing tests run fine.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] My code follows the code style of this project.
- [X] My change requires a change to the documentation.
- [X] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [X] All new and existing tests passed.

### CODE REVIEW

**Comment by marci4** [comment]
I think there is no need to patch this to 1.4.2, 1.5.0 should be fine

#1000 requires 1.7 API level https://docs.oracle.com/javase/8/docs/api/javax/net/ssl/SSLParameters.html#setEndpointIdentificationAlgorithm-java.lang.String-

Best regards,
Marcel

**Comment by marci4** [comment]
I think there is no good way to test this right?

**Comment by PhilipRoman** [comment]
Well, the functionality is implemented in JDK, so it's their responsibility. The getter/setter logic in our code is trivial, so I think that there is no point in testing it.

Theoretically we could prevent the server socket from accepting incoming sockets and see how many connections it takes to start dropping them, but then we would be simply testing JDK code.

**Comment by PhilipRoman** [comment]
If the only "breaking change" in 1.5.0 is a newer JDK version, then I agree about putting this in 1.5.0.

**Comment by PhilipRoman** [comment]
For some reason the test action was running for over 2.5 hours for the last commit, so I stopped it.

**Pull request merged**
