### PR TITLE
Merge pull request #943 from da-als/master

### LINKED ISSUE #665: Data read with end of SSL handshake is discarded
## Description

Essentially, the bug is that

CONCLUDE SSL HANDSHAKE
PLEASE CAN WE DO WEBSOCKETS

works, while

CONCLUDE SSL HANDSHAKE PLEASE CAN WE DO WEBSOCKETS

does not

## Expected Behavior

Data following the conclusion of the SSL handshake should be processed, regardless of how quickly it follows the handshake.

Websockets operating over SSL are ultimately using TCP, which is a streaming protocol, meaning that a given read() call will generally return all unclaimed data which has arrived, regardless of any logical boundaries, origin in distinct write() calls, or breaks between packets.

When operating as a server, the final read() call in processHandshake() in SSLSocketChannel2.java often ends up claiming not only the concluding 45 or so bytes of the SSL handshake exchange, but also 300-something bytes of immediately following HTTP traffic - typically the initial Websocket upgrade request.

## Current Behavior

Unfortunately, at least as of Java-WebSocket-1.3.0-334-g105e2e0 and preceding recent versions, any remaining data in the inCrypt buffer is dropped when processHandshake calls createBuffers().  This means that the websocket upgrade request contained within the dropped data buffer is never seen, and application programs on both ends fail to receive a connection callback.

## Possible Solution

We've had initial success modifying createBuffers() to not rewind/flip inCrypt if it contains yet unused data.  However, it's not clear if this is entirely safe or how it interacts with past bugfixes like that for #190.  It would also seem that if the buffer size should change the data could need to be copied from the old one to the new.

We are also unsure if this should be restricted to the createBuffers() call resulting from the SSL handshake's read() operation.  We only operate the library in the server role, and suspect that the SSL handshake completing during a write() would be more likely to occur in the complementary client role?

## Steps to Reproduce (for bugs)

The problem is most obvious when a client (or the TCP stack of the client's operating system) combines both the final piece of the SSL handshake and the following initial protocol traffic within the same packet.  Using daltoniam/Starscream on an iphone for example, initial connections seem to send these in distinct packets and the connection works.  But if the websocket is disconnected and new connection attempt made soon thereafter, the final piece of the new connection's SSL handshake and its initial data seem to reliably end up in the same packet, as a result of this bug the portion following the SSL handshake is dropped by createBuffers(), and the connection fails to establish a Websocket. (Packet sniffing shows that the client's source port does increment, so this is not a TCP connection confusion.  Additionally, distinct write() calls are actually being used for the SSL handshake vs. application data, but unless a few hundred milliseconds of delay in inserted in between, the operating system/TCP stack is merging them into a single packet for stream efficiency as the design of TCP encourages)

The problem can also theoretically occur if the client manages to fire off two distinct packets in between the server's read() calls, such as might happen if the server is heavily loaded or experiencing scheduler latency, or in the case of network level issues, especially as Nagle encourages sending an additional packet even with the ack of the previous still unreceived.

The situation could probably also be artificially caused by introducing a half-second sleep() before each read() call, such that all of the data the client intends to send at that point in the conversation will probably arrive before the read() can claim any of it.

Ultimately, communication over TCP needs to handle both the case of a read() call retrieving less than a logical chunk of data, and also the case of it retrieving the end of one logical chunk and all or part of another.  Because of the buffer clearing, the latter case is not handled at the specific transition which occurs at the end of the SSL handshake.

## Context
Android based secure websocket server is unable to reliably accept websocket connection attempts from clients behaving in accordance with the TCP specification.

## Your Environment
Android 6.1 with Java-WebSocket-1.3.0-334-g105e2e0 operating in server role
Secure Websockets
Client using https://github.com/daltoniam/Starscream v 3.0.4 on iOS 11.0.2
both server and client on the same local wifi network

### LINKED ISSUE #940: WebSocket handshake fails over WSS, if client uses TLS False Start
**Describe the bug**
If client uses TLS False Start, WebSocket handshake data sent from client gets thrown away in server.
Related to #466 and #665.
TLS False Start (https://tools.ietf.org/html/rfc7918) means the client can start sending application data immediately after sending ChangeCipherSpec and Finished messages during the TLS handshake, as opposed to having to wait for the server to respond with its ChangeCipherSpec and Finished messages.
The issue is similar to #665 in that any remaining data in the inCrypt buffer is dropped when processHandshake calls createBuffers(), but applying the fix proposed in #665 is only part of the solution, because in this case the data is received during the handshake and when handshake completes, no additional SSLSocketChannel2.read is attempted, which would restore the data. Not sure why, I haven't looked further than SSLSocketChannel2 in the code.

#466 was also caused by this issue.
https://github.com/TooTallNate/Java-WebSocket/issues/466#issuecomment-298877689
Java 8 does support TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256, the cipher suites mentioned in the SO post and which aren't supported by default with the limited crypto policy are AES_256 ciphers.
Disabling this cipher suite "fixed" the issue because TLS False Start can be used by the client when certain preconditions are met, one of which is a whitelisted cipher suite (TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 is one of them). When this cipher suite is removed, TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA (in my case) gets negotiated, which isn't whitelisted.

**To Reproduce**
Use Firefox, has false start enabled by default (can be disabled in about:config security.ssl.enable_false_start). Can play around with this setting to make sure the issue is occurring because of TLS False Start.
Not reproducible with Chrome: did have TLS False Start enabled at some point, but is disabled by default now and only enabled if server supports ALPN (Application-Layer Protocol Negotiation): https://arstechnica.com/information-technology/2012/04/google-abandons-noble-experiment-to-make-ssl-less-painful/
Use CustomSSLWebSocketServerFactory with all cipher suites enabled (DefaultSSLWebSocketServerFactory disables TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 as of v1.3.4).
Use some packet sniffing tool to make sure TLS False Start occurs. Won't occur when TLS session resumption gets used.

**Environment:**
 - Version used: 1.4.0
 - Java version: 1.8
 - Operating System and version: Win 7
 - Endpoint Name and version: Firefox 69.0

### PR DESCRIPTION
**Pull request by da-als**
## Description
This pull request includes a fix developed by @doyledavidson where any data located after the end of a SSL handshake is saved to be returned on the next read operation. This way, the data is not lost and connections from clients that append data at the end of the handshake do not have trouble communicating with Java-WebSocket.

## Related Issue
Fixes #665
Fixes #940

## Motivation and Context
Some clients, when connecting to a WSS server, use TLS False Start, which causes initial data to be appended to the SSL handshake. That data gets discarded by the Java-WebSocket server which often causes communication problems, even causing the connection to become unresponsive for the client as it waits for a reply from the server.

## How Has This Been Tested?
I use the Java-WebSocket library on an application that acts as a local server on hundreds of clients that access this server functionality from a regular web browser. Clients that are using browsers that use TLS False Start often required multiple connection attempts to work around the issue, and even that, in some cases, was not enough. I have deployed my fork of this library with a new beta of my application on about a dozen clients for testing; they are not running into the issue anymore (connections work on the first try) and no regressions have been reported.

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

Once again, the code was added by @doyledavidson, not myself. I am not familiar with the process for running the tests, but since it affects new connections' handshakes and their first read operations I would assume the changes would be fully covered by existing tests.

### CODE REVIEW

**Comment by marci4** [comment]
@PhilipRoman thx, I will try it when I have some time on my hands.

**Comment by marci4** [comment]
I had some problems running this.
The autobahn testsuite failed a few times for me.
Anyone else tried it?

**Comment by da-als** [comment]
> I had some problems running this.
> The autobahn testsuite failed a few times for me.
> Anyone else tried it?

After your report I tried running all the tests in the project. The only test that failed for me was "Issue256Test", but this one also fails without the changes from the merge (it fails on the master branch of the main project) so it has no relation to this pull request.

**Comment by marci4** [comment]
@da-als I was running it against the big websocket autobahn test suite, which is not part of the normal unit test.

Currently, really busy, so I did not have more time to take a look at this sorry..

**Comment by jiangjianping** [comment]
@da-als 
thank you very much. This almost reosolved my issue #958

**Comment by marci4** [comment]
I havent forgotten this PR, currently just very busy...

**Comment by marci4** [comment]
@da-als thx a lot for your contribution!

**Comment by da-als** [comment]
@marci4 Happy to help! Glad to see the fix merged.

**Comment by doyledavidson** [comment]
Thank you everyone for getting that pulled in!

**Comment by doyledavidson** [comment]
Any plan to push a new version (1.4.1?) to Maven repo?

**Comment by marci4** [comment]
@doyledavidson a snapshot should be available

**Pull request merged**
