### PR TITLE
Fixed Javadoc errors

### PR DESCRIPTION
**Pull request by garys-esri**
These error cause the Maven build not to complete.

### CODE REVIEW

**Comment by garys-esri** [comment]
Thanks! Great repo by the way!

**Comment by BrushfireDigitalServices** [comment]
Thanks for your contribution, @garys-esri! We're striving to make this repo even better, and having accurate Javadocs is a big part of that.

If your project uses WSS and this library is working great, please consider describing/linking to the use case in the discussion at the positive-report issue #325.

**Comment by garys-esri** [comment]
Done: https://github.com/TooTallNate/Java-WebSocket/issues/325#issuecomment-126029382

**Comment by BrushfireDigitalServices** [comment]
Much appreciated!

**Pull request merged**
