### PR TITLE
Using Google Java Code Style To Reformat Code

### LINKED ISSUE #1050: What about adding the CodeFormatterProfile.xml with the code format ?
Current code format is unfriendly, such as using tabs for indentation. What is more,  not all existing code follow the current code format.
@PhilipRoman

### PR DESCRIPTION
**Pull request by dota17**
## Description
The current code format is not very good, especially when reading the code online on github. I can't stand this anymore.

I chose Google Java Code Style to reformat the source code.
The reason why I chose Google's version:
1. There is a [repo](https://github.com/google/styleguide) for the code format profile.
2. There are 2 predefined Checkstyle configuration definitions that ship with the Maven Checkstyle Plugin, and the Google definition is the one. We can use it to help checking the code style.

I would consider adding the google checkstyle next and optimize the code format further.

## Related Issue

Fixes #1050

## How Has This Been Tested?

All new and existing tests passed.

## Types of changes

I choose the `intellij-java-google-style.xml` and import in IDEA, and then reformat code with the tools.
The main change is the source code in the src directory.

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by marci4** [comment]
@dota17 you think it is worth to enforce the style via github action?

Best regards,
Marcel

**Comment by dota17** [comment]
IMO, it is worth.

You can refer to the Apache Projects. When people submit their code to the repository, the code reviewer will always prompt the submitter to reformat code to meet the code style.

**Comment by marci4** [comment]
Sounds good, can you setup a github action for that?

**Comment by dota17** [comment]
Yes, I can. But I don't have the permissions to configure.

**Comment by marci4** [comment]
You should be able to edit the github actions in your fork and merge with this PR

**Comment by dota17** [comment]
OK, I will do it.

**Review by marci4 — CHANGES_REQUESTED** [review]
Please include an action to check for the correct formatation

**Comment by dota17** [comment]
Sorry, I was a little busy last week. I'll take care of it as soon as possible.

**Comment by marci4** [comment]
@dota17 all good. Just wanted to write down why this PR is not yet merged.
Keep in mind, you don't have to do anything and you really don't have to be sorry for not having the time.
We all do this in our free time :)

**Comment by dota17** [comment]
There are some check points that we should discuss here, such as `OverloadMethodsDeclarationOrder` and `NonEmptyAtclauseDescription`. You can see them in the github actions - [`Java Code Style Check with Maven`](https://github.com/TooTallNate/Java-WebSocket/pull/1060/checks?check_run_id=1025740250)

If we want to ignore the check points, we can add more filters in the file - `checkstyle-suppressions.xml`. If we won't, just need to modify the code.

**Comment by marci4** [comment]
I think we can ignore OverloadMethodsDeclarationOrder and NonEmptyAtclauseDescription

**Review by marci4 — APPROVED** [review]

**Comment by marci4** [comment]
@dota17 ping me when you are happy with the PR

**Comment by dota17** [comment]
@marci4 It is ready to be merged.

**Pull request merged**
