### PR TITLE
Integrated an SSLSocketChannel class that allows wss support

### PR DESCRIPTION
**Pull request by fomojola**
I integrated an SSLSocketChannel class (taken from the jFxp project at http://jfxp.sourceforge.net/ with permission by the author, Alexander Kout) and modified the WebSocketImpl to allow the use of that instead of a standard SocketChannel.

Also added a simple SSL example that uses a self-signed certificate. The example/SSLServer.java includes a really simple test case that uses a keystore generated using keytool (the keytool syntax is present in that file as a comment, as well as the keystore loading code required).

### CODE REVIEW

**Comment by blunden** [comment]
I agree with @mparis, it would be great if you could update the outdated maven central release. Lots of developers prefer to pull down their dependencies from there.

**Comment by mfsi-ankitb** [comment]
Actually yes, I too agree with @blunden, can you guys please update the maven central.
I am on live project and really need to use WebSockets having WSS enabled with lollipop.

**Comment by blunden** [comment]
@mfsi-ankitb The issue might be that it still has problems with working on both 5.0 and earlier versions. See https://github.com/TooTallNate/Java-WebSocket/issues/293

**Comment by mfsi-ankitb** [comment]
@blunden I tried using Java-WebSocket with the latest source code, and it is working for me on lollipop with WSS (using default SSLcontext).

**Comment by blunden** [comment]
@mfsi-ankitb Oh, really? Did you confirm that it works with earlier Android versions too?

I personally switched to a different lib for that issue. I know of others who would be interested to know that it has been fixed though.

**Comment by mfsi-ankitb** [comment]
@blunden Yes, the connection opens and I am able to send and receive messages (checked in 5.0 and 4.1.1). But, facing some problems like connection breaks (doesn't connect back) when Internet Connectivity drops and reconnect again. And I can't connect back with same client once disconnect is triggered.

**Comment by blunden** [comment]
@mfsi-ankitb Thanks for the confirmation! 

Yeah, you will need to recreate the WebSocket related objects. That seems to be the case in many WebSocket libraries. Perhaps you can reconnect in some onWebSocketError-like method?

**Pull request merged**
