### PR TITLE
ConcurrentModificationException when using broadcast

### PR DESCRIPTION
**Pull request by marci4**
## Description

It is possible to have get a ConcurrentModificationException when using broadcast and a new client connects/drops

## Related Issue

Found with #879

## Motivation and Context

Bugfix

## How Has This Been Tested?

Developed test

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I have added tests to cover my changes.
- [X] All new and existing tests passed.

### CODE REVIEW

**Comment by maiph** [comment]
Wouldn't it be better to make a copy of the list of clients inside a synchronization block and then loop over it?
Also, having it this way wouldn't it block the server thread while all the frames are being created ? And therefore block any operations on the clients list.

**Comment by marci4** [comment]
@maiph yeah good point. Will change it later!

**Comment by marci4** [comment]
@maiph could you maybe give me feedback to my second changes? Thank you :)

**Comment by hovis** [comment]
The implementation of getConnections() should also be synchronized on the connections variable whilst it does a new ArrayList()

**Comment by marci4** [comment]
@hovis please open an fresh issue and a new PR. Thanks

**Pull request merged**
