### PR TITLE
add host param base Draft_6455

### PR DESCRIPTION
**Pull request by TOTOROYang**
add host param base Draft_6455

### CODE REVIEW

**Comment by TOTOROYang** [comment]
I renamed and add some description.

**Comment by marci4** [comment]
Hello @TOTOROYang,
thx a lot for the changes!

Added it to the master branch!

Greetings
marci4

**Comment by marci4** [comment]
Hello @TOTOROYang,

after reading through the spec and some issues, a non browser websocket client does not have to send a orogin-header.
That is why I am removing this draft again.
Please open a issue at the specific project to let them support non browser clients.

Greetings
marci4

**Comment by TOTOROYang** [comment]
wss://apprtc-ws.webrtc.org:443/ws
you can try to connect this webSocket server.
I find out this webSocket (use go) need origin.
i find it at http://websocket.org/echo.html.

**Comment by marci4** [comment]
Hello @TOTOROYang,

The following is out of the spec ([1.3](https://tools.ietf.org/html/rfc6455#section-1.3)):
`  The |Origin| header field [RFC6454] is used to protect against
   unauthorized cross-origin use of a WebSocket server by scripts using
   the WebSocket API in a web browser.  The server is informed of the
   script origin generating the WebSocket connection request.  If the
   server does not wish to accept connections from this origin, it can
   choose to reject the connection by sending an appropriate HTTP error
   code.  This header field is sent by browser clients; for non-browser
   clients, this header field may be sent if it makes sense in the
   context of those clients.`

The origin field is not required by the spec and for me it is not right in the current context.

Greetings
marci4

**Pull request merged**
