### PR TITLE
Use appropriate schema in any case

### LINKED ISSUE #1026: Force client to use the valid schema
**Is your feature request related to a problem? Please describe.**

Yes.

When I use the invalid schema(https, http) with explicit port in uri
```
//dev config, host=domain:port

String url = String.format("http://%s/%s", host, "websocket");

ws = new WebSocketClient(new URI(url)) 
```

MayBe, I can't find the potential the problem, because it can run without exception.

But, it will failed when we omit the port in uri. and It will throw an exception:"unkown schema http"

```
// prod config, host=domain

String url = String.format("http://%s/%s", host, "websocket");

ws = new WebSocketClient(new URI(url)) `

```
 
I'm alway frustrated when run failed only with different config in prod environment.

I think we should allow user to find the potential problem during development. 

**Describe the solution you'd like**

always check the schema and throw exception on invalid schema,  regardless whether the port is explicit set(no matter uri.getPort() == -1).

### PR DESCRIPTION
**Pull request by yindex**
Enforce Use appropriate schema in any case
## Description

throw exception if use invalid schema in websocket client.
## Related Issue
Fixes #1026 

## Motivation and Context

I think we should force users to use valid schema. Avoid confusion when using the invalid schema without throwing an exception
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by marci4** [comment]
Hello @yindex,

could you please open a PR for this issue so everyone better understands the issue.
Thx a lot.

Best regards,
Marcel

**Comment by yindex** [comment]
sorry, for miss that, I will open an issue with detail and Motivation for that

**Comment by yindex** [comment]
> Hello @yindex,
> 
> could you please open a PR for this issue so everyone better understands the issue.
> Thx a lot.
> 
> Best regards,
> Marcel

an issue #1026   for the PR has been open

**Comment by yindex** [comment]
> Changes look good.
> Could you create two simple tests which simple check for the illegal argument exception when using http and https and no exception when using ws and wss

two sample test added

Best regards,
yindex

**Comment by marci4** [comment]
@yindex thx for your changes and the tests!

Best regards,
Marcel

**Pull request merged**
