### PR TITLE
WebSocketServer code quality

### PR DESCRIPTION
**Pull request by marci4**
## Description

Refactoring as part of improving the code quality

## Related Issue

Part of #749 

## Motivation and Context

Code quality helps fixing issues!

## How Has This Been Tested?

All tests pass

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by marci4** [comment]
@PhilipRoman Conflict is not relevant FYI

**Comment by PhilipRoman** [comment]
GitHub is not letting me "review" at the moment so I'm leaving this here. The changes are awesome! I didn't check all the tests but the ones I checked are good. 👍

**Comment by PhilipRoman** [comment]
GitHub is not letting me "review" at the moment so I'm leaving this here. The changes are awesome! I didn't check all the tests but the ones I checked are good. 👍

**Comment by PhilipRoman** [comment]
😆 I did not expect that to happen

**Pull request merged**
