### PR TITLE
Chat server high cpu usage

### PR DESCRIPTION
**Pull request by lifubang**
If there is no sleep, there will be about 20% cpu usage(4 cpu threads) without any websocket client connections, then some people will give up this websocket server solution.
I think that most of people create there websocket server from this example. When I got a 20% cpu usage, I want to give up this solution for a short time. But when I use jstack to analysis the code, I found this problem. After this fix, the cpu usage is down to 0-1% when there is no connection.

### CODE REVIEW

**Comment by marci4** [comment]
Hello @lifubang,

thx again for your pull request.

Well, I don't think most of the people use this main method for their projects even just in the beginning.
It is there to show new people how it works with extending and also overriding methods.

Do you see it different? If so, please tell me why.

Greetings
marci4

**Comment by lifubang** [comment]
I think Java-WebSocket project is the most simple one for websocket, but not the popular one because of missing extensive documentation. So I think most of people may start there first example with src/main/example/ChatServer.java.  In fact, this example provide most features of simple websocket server. All people may focus on server's performance when using websocket server, but when they got a 20% cpu usage, they may give up.

By the way, I think this project needs more features:
1. How to get url's params?
2. How to get client's cookie?
3. How to get client socket's unique key in onOpen, onClose, and onMessage method?

**Comment by marci4** [comment]
Hello @lifubang,

I am trying to catch up with all the missing documentation from the beginning of the project. Since it is an open source project you are very welcome to participate and help with that ;)

I personally still don't feel the need to change it since it is just to show new people how to use the library and it is never meant for production. 
I still will look into this when I am back home and maybe think of a good way not to sleep the main thread.

Please comment on the issues, if there is one already, or create new issues for your requests. I will not discuss them in a total different pull request.

Greetings 
marci4

**Comment by marci4** [comment]
Hello @lifubang,

I have no high cpu usage. Not in my IDE as well as on my server..

Closing this since it is not relevant.
Greetings
marci4

**Pull request closed without merging**
