### PR TITLE
Created TLSWebSocketFactory that can be configured to only support gi…

### PR DESCRIPTION
**Pull request by rachidbm**
Added implementation of WebSocketServerFactory that can be configured to only support given protocols and given cipher suites.

### CODE REVIEW

**Comment by BrushfireDigitalServices** [comment]
Thank you for the pull request, @rachidbm! Sorry to have taken so long to respond.

I agree that this project needs a way to specify supported protocols and cipher suites. Your code looks like a good solution, with documentation included. Much appreciated!

Do you have any test or example code for TLSWebSocketFactory? Test coverage is a major item right now (#318), and it would be good to include as much as possible with each new addition.

**Comment by rachidbm** [comment]
Good to hear that contributions are appreciated. Although I do see the importance that test coverage, I didn't wrote a test because this class is mainly doing some settings. There's hardly any logic included which makes it worth testing (in my opinion). 

I just added an example in code ;)

**Comment by ThreaT** [comment]
@rachidbm I think we can achieve full test coverage if everyone adds tests `while they're at it` so to speak. Would you be willing to add a test for each method that you changed/added?

**Comment by rachidbm** [comment]
I don't think it's useful to add unit tests that directly cover the methods. But I do think it's helpful to have a test that starts a server with the TLSWebSocketFactory, and let a client trying to connect with different protocols. When a protocol is not configured in the TLSWebSocketFactory, connection should be refused be the server.
What do you think?

**Comment by ThreaT** [comment]
@rachidbm Similar to what I've [started doing](https://github.com/TooTallNate/Java-WebSocket/issues/318) for [acceptance tests](https://github.com/TooTallNate/Java-WebSocket/compare/master...ThreaT:master) then. That would be fine too.

**Pull request closed without merging**
