### PR TITLE
Add support for Java modules

### PR DESCRIPTION
**Pull request by anthonyvdotbe**
## Description

Add support for Java modules. The slf4j-api dependency was also updated to use a modularized version.

## Related Issue

#1308

## Motivation and Context

It allows projects that depend on this project to be modularized as well. And it allows encapsulating packages (such as the `utils` package).

## How Has This Been Tested?

Building the project and verifying that the created JAR is now modular with `jar -d -f .\Java-WebSocket-1.5.4-SNAPSHOT.jar --release 9`

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by PhilipRoman** [comment]
Hi, I would like to merge this, but from what I see this is a breaking change - slf4j api requires java 8 after version 2.0.0 and the new build process requires at least java 9.
From README it seems like we currently promise JDK 7 compatibility.

@marci4 what are your thoughts on this?

If modules and slf4j-api are the only thing we need from java 9, and codebase remains java 7 compatible, maybe it makes sense to build two jars and release the new one under different name.

**Comment by marci4** [comment]
@PhilipRoman java 7 is only needed for android, but as far as I know these versions are still supported by google (they have at least access to the playstore) so I dont think we can drop this support.

We had a lot of problems when we used a java 7 api (https://github.com/TooTallNate/Java-WebSocket/wiki/No-such-method-error-setEndpointIdentificationAlgorithm) so...

**Comment by PhilipRoman** [comment]
Looks like CI is failing
https://github.com/TooTallNate/Java-WebSocket/actions/runs/4357698514

```
Run actions/setup-java@v[3](https://github.com/TooTallNate/Java-WebSocket/actions/runs/4357698514/jobs/7617329596#step:3:3)
  with:
    java-version: 1[7](https://github.com/TooTallNate/Java-WebSocket/actions/runs/4357698514/jobs/7617329596#step:3:7)
    java-package: jdk
    check-latest: false
    server-id: github
    server-username: GITHUB_ACTOR
    server-password: GITHUB_TOKEN
    overwrite-settings: true
    job-status: success
    token: ***
Error: Input required and not supplied: distribution
```

**Comment by anthonyvdotbe** [comment]
@PhilipRoman my bad. The [docs](https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven#using-the-maven-starter-workflow) also have a `distribution` attribute. I assumed it was optional, but apparently it isn't. Would you mind to add the attribute yourself? Or do you want me to provide a PR for it? Either way, sorry for the trouble.

**Comment by PhilipRoman** [comment]
Thanks for adding it, I have no idea how Github CI works 😆

**Pull request merged**
