### PR TITLE
Added Clojure project.clj for easy compile and deploy of 1.3.1

### PR DESCRIPTION
**Pull request by jasminsehic**
Now we can use clojars.org repo
Updated build.gradle and project.clj to version 1.3.1

### CODE REVIEW

**Comment by daluu** [comment]
Is it actually fully working for clojars.org repo? Or one must actually use Clojure/Leiningen to use the JAR stored there?

I thought to give it a try with my maven pom & this was the result snippet below (running `mvn eclipse:eclipse`). I wasn't able to pull the JAR/POM for 1.3.1 nor 1.3.0 (tested manually via pasting URL to browser), but was able to pull 1.3.0 from maven central by URL just no 1.3.1 available.

For maven pom, I simply inserted the clojar maven repository snippet & the maven dependency snippet from clojars.org into my pom file, following https://clojars.org/org.java-websocket/java-websocket

```
Downloading: http://clojars.org/repo/org/java-websocket/Java-WebSocket/1.3.1/Java-WebSocket-1.3.1.pom
Downloading: https://repo.maven.apache.org/maven2/org/java-websocket/Java-WebSocket/1.3.1/Java-WebSocket-1.3.1.pom
[WARNING] Missing POM for org.java-websocket:Java-WebSocket:jar:1.3.1
Downloading: http://clojars.org/repo/org/java-websocket/Java-WebSocket/1.3.1/Java-WebSocket-1.3.1.jar
Downloading: https://repo.maven.apache.org/maven2/org/java-websocket/Java-WebSocket/1.3.1/Java-WebSocket-1.3.1.jar
[WARNING] An error occurred during dependency resolution.
    Failed to retrieve org.java-websocket:Java-WebSocket-1.3.1
Caused by: Could not find artifact org.java-websocket:Java-WebSocket:jar:1.3.1 in clojars.org (http://clojars.org/repo)

Try downloading the file manually from the project website.

Then, install it using the command: 
    mvn install:install-file -DgroupId=org.java-websocket -DartifactId=Java-WebSocket -Dversion=1.3.1 -Dpackaging=jar -Dfile=/path/to/file

Alternatively, if you host your own repository you can deploy the file there: 
    mvn deploy:deploy-file -DgroupId=org.java-websocket -DartifactId=Java-WebSocket -Dversion=1.3.1 -Dpackaging=jar -Dfile=/path/to/file -Durl=[url] -DrepositoryId=[id]

Path to dependency: 
	1) your maven project
	2) org.java-websocket:Java-WebSocket:jar:1.3.1


  org.java-websocket:Java-WebSocket:jar:1.3.1

from the specified remote repositories:
  clojars.org (http://clojars.org/repo, releases=true, snapshots=true),
  central (https://repo.maven.apache.org/maven2, releases=true, snapshots=false)

[INFO] Unable to read jar manifest from /Users/daluu/.m2/repository/org/java-websocket/Java-WebSocket/1.3.1/Java-WebSocket-1.3.1.jar
```

**Comment by bendem** [comment]
There are currently 3 build system included in the repo and only 1 is up to date...

**Comment by daluu** [comment]
Which one is up to date? 

My question/point was that it appears the clojars repo isn't fully working, although I didn't test from the Clojure side. But from what I saw on the clojars.org site (docs), it appears you can use maven to fetch from that repo so you aren't restricted to pulling with Leiningen (or other Clojure toolkit). Attempting the maven fetch against clojars repo fails as per my previous comment.

**Comment by bendem** [comment]
The pom.xml is up to date, latest released version is 1.3.0, current head is 1.3.1-SNAPSHOT

**Comment by daluu** [comment]
but I'm curious why trying to fetch from clojars repo via a maven pom.xml in my own project for this dependency (or from the error dump, trying to fetch with direct URL to clojars repo) fails. I don't know the workings of clojars repo but I know for maven central, you are able to pull with maven as well as directly fetch by URL link in repo (the maven central page for a hosted JAR even has link to download the JAR that maven also uses to pull the JAR from I believe.

The question isn't about whether the files are correct but why what was published to clojars doesn't seem to be available. I mean take a look at this page:

https://clojars.org/org.java-websocket/java-websocket

and last comment by @jasminsehic at https://github.com/TooTallNate/Java-WebSocket/issues/252, maybe @jasminsehic can answer this.

**Comment by marci4** [comment]
Hello @jasminsehic 

could you give me access to this repository? (Using the username marci4)

Thx!
Greetings
marci4

**Comment by marci4** [comment]
Hello @jasminsehic,

sorry that my message was misleading...
I meant the https://clojars.org/ dashboard.

Greetings
marci4

**Comment by jasminsehic** [comment]
@marci4 I have added you to Clojars

**Pull request merged**
