### PR TITLE
Fix e race problem when starting server with port 0 (issue 362)

### PR DESCRIPTION
**Pull request by PerBothner**
I'm starting the server with a port of 0, so I can then immediately
open a client of the server, without hard-wiring in a specific
port. Before I start the client, I need to call getPort(). But that
may not work, since the server field may not have been set yet, and
that happens in a separate thread. My suggestion is to move the
initial socket.bind to the start method, before the run method in the
new thread.

### CODE REVIEW

**Comment by PerBothner** [comment]
See issue #362 .

**Comment by marci4** [comment]
Hello @PerBothner 
thinking about your pull request again.

Would it also just be sufficient for you to get a notification that the server startet up successfully?

Greetings
marci4

**Comment by PerBothner** [comment]
No, because if the requested port number is zero, I also need to know the actual port number.

Note I am no longer using Java-WebSocket (I'm using libwebsockets instead), so this is no longer an issue for me or my projects.

**Comment by PerBothner** [comment]
I may have misunderstood the question: The problem is solved if I can reliably get the actual port number after start-up.

(However, I'm still sticking with libwebsockets.  Glad to see this project is alive again, though.)

**Pull request closed without merging**
