### PR TITLE
 Give all threads a custom name 

### LINKED ISSUE #666: Give the main WebSocketClient thread and AbstractWebSocket Timer a name
Only the read thread is assigned a name in a `WebSocketClient` instance. The main `Runnable` acquires a default name like "Thread-7". I'm working on an application where I need to identify threads and manage them, and it would be nice to be able to distinguish them purely by name instead of inspecting their stack trace. 

According to `oakkitten` who it pointed out in [this thread](https://github.com/TooTallNate/Java-WebSocket/pull/464), the [`connect()` method](https://github.com/TooTallNate/Java-WebSocket/blob/master/src/main/java/org/java_websocket/client/WebSocketClient.java#L265-L270) creates a `writeThread` field which is [overwritten with a new `WebsocketWriteThread`](https://github.com/TooTallNate/Java-WebSocket/blob/master/src/main/java/org/java_websocket/client/WebSocketClient.java#L380-L381) when the thread runs. `WebsocketWriteThread` sets the name, but the thread started in the `connect()` method continues to run with the default name.

Additionally `oakkitten` noted that a new `Timer` is [created](https://github.com/TooTallNate/Java-WebSocket/blob/a5ff3b4bb213767c13b24f0d2e6363d4ff874cd4/src/main/java/org/java_websocket/AbstractWebSocket.java#L131) in `AbstractWebSocket` and it also lacks a name.

### PR DESCRIPTION
**Pull request by marci4**
## Description

All threads should have a custom name
Also added getConnections() to return an unmodifiable list

## Related Issue

Fixes #666 

## Motivation and Context

Clear names and clean up

## How Has This Been Tested?

Issue666Test

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by oakkitten** [comment]
while [the variable](https://github.com/marci4/Java-WebSocket-Dev/blob/2047167f1d3d98b0f88314bad3828db022dc9d72/src/main/java/org/java_websocket/client/WebSocketClient.java#L269) is named `writeThread`, the thread in question is not a writing thread, but a connecting/reading thread. also, `getId()` returns a number that uniquely identifies all threads, while it would be nice to have the threads working “together” having the same number (e.g. `WebSocketWriteThread-1`, `WebSocketConnectReadThread-1` and `WebSocketTimer-1`)

**Comment by marci4** [comment]
Hello @oakkitten,

thank you for the feedback.
The question is, if the getId() information is more important then "workspace-id". 
I personally think that most of the users expect the id at the end to represent getId().

I also cannot add getId() to the constructor of Timer since the thread does not exist yet.

Do you think there is any benefit using the "workspace-id"? Like for most of the users which just run one connection.

Could you also just open a simple pull request for the wrong name? Thank you! :)

Greetings
marci4

**Comment by oakkitten** [comment]
in my app, i only run one connection, but when there's a connection drop i reconnect, and my logging system logs thread names, and it's nice to know that i had a problem with `WebSocketWriteThread-1` and not `WebSocketWriteThread-2`, for instance. also, things like `Timer` use their own serial numbering for their threads, so it seems that different “kind” of threads should use their own increments. well, just my opinion, anyways

now while it's easy to have the same number for writing/reading threads, i'm not sure if threads that are not created each time, such as that `WebSocketTimer` thing again, should have the “workspace” number. that is, if i create and destroy 3 connections, i create and destroy `WebSocketWriteThread-0`, `-1`, and `-2` but i might have only created one single `WebSocketTimer`; now should the next `WebSocketTimer` be called `WebSocketTimer-1` or `WebSocketTimer-3`?

aaand perhaps `WebSocketTimer` can be something more descriptive like `ConnectionLostTimer` or `-Watcher` or maybe `PingTimer`, since it also sends pings?

**Comment by marci4** [comment]
For me the biggest problem with the workspace id is that you have to set it on your WebSocket instance yourself since it cannot know that there was a WebSocket running already (e.g. two instances where stopped, you start a new one --> ID = 1 even though it should be 3.

No you cannot reuse the `Timer` for multiple connections, each WebSocket gets its own timer.


Yeah I see, I'm not really good at naming stuff ;) 
Will change this then!

Apart from that, I added a method to reconnect a `WebSocketClient` in 1.3.8. You may wanna check this out ;)

Thanks again for the feedback!
Greetings
marci4

**Comment by oakkitten** [comment]
> set it on your WebSocket instance yourself

why not go the usual way and use a static atomic integer?

> No you cannot reuse the Timer`

i cannot, but i can disconnect before i'm connected, in this case the `Timer` just doesn't get created

**Comment by marci4** [comment]
I will take a look at this again.

Thank you for your feedback :) Much appreciated!

Greetings
marci4

**Pull request merged**
