### PR TITLE
added a timeout option for connectBlocking

### PR DESCRIPTION
**Pull request by cymp**

### CODE REVIEW

**Comment by cymp** [comment]
Well I didn't find a code style settings for this project Which one should I use?

**Comment by PhilipRoman** [comment]
CodeFormatterProfile.xml at project root

**Comment by cymp** [comment]
Wow sorry...

**Comment by PhilipRoman** [comment]
Tested it, everything works as expected.

**Comment by cymp** [comment]
@PhilipRoman 
Are there any snapshot release, how am I supposed to be able to download via maven what I just did ?

**Comment by PhilipRoman** [comment]
Not sure what's the best way for this project (I don't use maven for dep management) but as a quick fix, you can always `git clone`, then `mvn package` and add the jar as a local library to your project (until next release).

**Comment by marci4** [comment]
@PhilipRoman, gratz on your first merged PR! :)

**Pull request merged**
