### PR TITLE
Correct web socket closing

### PR DESCRIPTION
**Pull request by Serpion-ua**
Correct web socket closing in case if Server caught error

### CODE REVIEW

**Comment by Serpion-ua** [comment]
@marci4 reopened PR

**Comment by Serpion-ua** [comment]
@PhilipRoman could you please take a look? Thanks.

**Comment by PhilipRoman** [comment]
I'm looking at it right now and as far as I can see, there are 3 changes:
1. new option to pass message as parameter to `stop()`
2. in `handleFatal()`, WebSocketWorker shutdown loop moved after call to `stop()`
3. `ws.close()` not happening when catching fatal error in `run()`

Can you explain what 2. and 3. are supposed to do?

**Comment by Serpion-ua** [comment]
@PhilipRoman 
2. Yes, it allows us to correctly stop the server by sending the correct close message to the clients. Previously we try to send such messages by calling stop() AFTER selector/worker threads are stopped, thus no close messages are reached to clients. Now we will first send such messages to the clients and only after stop threads.
3. We no longer require such closing because we now correctly close socket in `handleFatal()`

Overall, you could reproduce the problem at current master branch by removing `ws.close()` in fatal error handling and launch (as you mentioned in 3 change) `org.java_websocket.issues.Issue1160Test#fatalErrorShallNotBeHandledByServer` test. That test expect to receive a close message at the client but will never get it. With that change close message are successfully received by the client.

**Review by PhilipRoman — APPROVED** [review]

**Pull request merged**
